apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: suha-uat
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/muneerkh/suha-app.git'  # Replace with your Helm chart repo
    targetRevision: main  # Replace with the branch name you’re using
    path: .
    helm:
      valueFiles:
        - values-uat.yaml
  destination:
    server: 'https://kubernetes.default.svc'  # For in-cluster deployment
    namespace: uat-suha                  # Replace with the target namespace for UAT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
